package dev.aurakai.auraframefx.data.offline

import kotlinx.serialization.Serializable

// --- New Data Class Definition ---
@Serializable
data class SystemMonitoringConfig(
    val enabled: Boolean = false,
    val batteryThresholdLow: Int = 20, // Percentage
    val batteryOptimizationEnabled: Boolean = false,
    val networkChangeMonitoringEnabled: Boolean = false,
    val appUsageAnomalyDetectionEnabled: Boolean = false,
    val securityScanIntervalHours: Int = 24,
    // TODO: Add more monitoring parameters as needed
)

// --- Placeholder definitions for other data classes referenced by CriticalOfflineData ---
// These should be fleshed out or replaced by actual definitions if they exist elsewhere.

@Serializable
data class OfflineAIConfig(
    val defaultAuraResponses: Map<String, String> = emptyMap(),
    val defaultKaiResponses: Map<String, String> = emptyMap(), // Added based on KaiAIService logic
    val lastSyncTimestamp: Long = 0L,
    // Add other AI-related offline configurations if needed
)

@Serializable
data class OfflineUserPreferences(
    val theme: String = "system_default",
    val preferredUnits: String = "metric",
    // Add other user preferences
)

@Serializable
data class OfflineConversationHistory(
    val messages: List<String> = emptyList(), // Simplified, could be List<AgentMessagePlaceholder>
    // Add other history-related fields
)

@Serializable
data class OfflineUIConfigs(
    val showTooltips: Boolean = true,
    val compactMode: Boolean = false,
    // Add other UI configuration settings
)

@Serializable
data class ContextualMemory(
    val lastUpdateTimestamp: Long = 0,
    val keyInsights: Map<String, String> = emptyMap(), // Key-value pairs for learned facts
    val userPreferencesDerived: Map<String, String> = emptyMap(), // E.g., "favorite_color": "neon blue"
    val importantSystemStates: Map<String, String> = emptyMap(), // E.g., "last_boot_time": "...", "network_status": "offline"
    val recentKeywords: List<String> = emptyList(), // Recently discussed keywords
    val summaryOfPastInteractions: String = "", // A condensed summary generated by AI
)


// --- CriticalOfflineData definition including the new SystemMonitoringConfig ---
@Serializable
data class CriticalOfflineData(
    val lastFullSyncTimestamp: Long = 0,
    val aiConfig: OfflineAIConfig = OfflineAIConfig(),
    val userPreferences: OfflineUserPreferences = OfflineUserPreferences(),
    val conversationHistory: OfflineConversationHistory = OfflineConversationHistory(),
    val uiConfigs: OfflineUIConfigs = OfflineUIConfigs(),
    val contextualMemory: ContextualMemory = ContextualMemory(),
    val systemMonitoring: SystemMonitoringConfig = SystemMonitoringConfig(), // NEW PROPERTY
)
