/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param targetLocation Where to store the backup (e.g., \"cloud\", \"local_sd_card\", \"oracle_drive\").
 * @param includeLogs Whether to include system logs in the backup.
 * @param includePreferences Whether to include user preferences in the backup.
 */
@Serializable

data class BackupRequest(

    /* Where to store the backup (e.g., \"cloud\", \"local_sd_card\", \"oracle_drive\"). */
    @SerialName(value = "targetLocation")
    val targetLocation: kotlin.String,

    /* Whether to include system logs in the backup. */
    @SerialName(value = "includeLogs")
    val includeLogs: kotlin.Boolean? = false,

    /* Whether to include user preferences in the backup. */
    @SerialName(value = "includePreferences")
    val includePreferences: kotlin.Boolean? = true,

    )

