/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param prompt The text prompt for content generation.
 * @param maxTokens Maximum number of tokens for the generated text.
 * @param temperature Controls the randomness of the output. Higher values mean more random.
 */
@Serializable

data class GenerateTextRequest(

    /* The text prompt for content generation. */
    @SerialName(value = "prompt")
    val prompt: kotlin.String,

    /* Maximum number of tokens for the generated text. */
    @SerialName(value = "maxTokens")
    val maxTokens: kotlin.Int? = 500,

    /* Controls the randomness of the output. Higher values mean more random. */
    @SerialName(value = "temperature")
    val temperature: kotlin.Float? = 0.7f,

    )

