/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param codeSnippet The AI-generated code snippet.
 * @param explanation An explanation of the generated code (optional).
 */
@Serializable

data class GenerateCodeResponse(

    /* The AI-generated code snippet. */
    @SerialName(value = "codeSnippet")
    val codeSnippet: kotlin.String,

    /* An explanation of the generated code (optional). */
    @SerialName(value = "explanation")
    val explanation: kotlin.String? = null,

    )

