/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param language The programming language for code generation (e.g., \"Kotlin\", \"Python\").
 * @param description Natural language description of the code to generate.
 * @param context Additional context or existing code for better generation.
 */
@Serializable

data class GenerateCodeRequest(

    /* The programming language for code generation (e.g., \"Kotlin\", \"Python\"). */
    @SerialName(value = "language")
    val language: GenerateCodeRequest.Language,

    /* Natural language description of the code to generate. */
    @SerialName(value = "description")
    val description: kotlin.String,

    /* Additional context or existing code for better generation. */
    @SerialName(value = "context")
    val context: kotlin.String? = null,

    ) {

    /**
     * The programming language for code generation (e.g., \"Kotlin\", \"Python\").
     *
     * Values: Kotlin,Python,Java,JavaScript,TypeScript,Swift,CPlusPlus,CHash
     */
    @Serializable
    enum class Language(val value: kotlin.String) {
        @SerialName(value = "Kotlin")
        Kotlin("Kotlin"),

        @SerialName(value = "Python")
        Python("Python"),

        @SerialName(value = "Java")
        Java("Java"),

        @SerialName(value = "JavaScript")
        JavaScript("JavaScript"),

        @SerialName(value = "TypeScript")
        TypeScript("TypeScript"),

        @SerialName(value = "Swift")
        Swift("Swift"),

        @SerialName(value = "C++")
        CPlusPlus("C++"),

        @SerialName(value = "C#")
        CHash("C#");
    }

}

