/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param instruction The instruction or query for the orchestrator to manage.
 * @param targetAgents Specific agents to involve in the orchestration (optional).
 */
@Serializable

data class OrchestrationRequest(

    /* The instruction or query for the orchestrator to manage. */
    @SerialName(value = "instruction")
    val instruction: kotlin.String,

    /* Specific agents to involve in the orchestration (optional). */
    @SerialName(value = "targetAgents")
    val targetAgents: kotlin.collections.List<@Contextual AgentType>? = null,

    )

