/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param agentType The AI agent joining the room.
 */
@Serializable

data class ConferenceRoomJoinRequest(

    /* The AI agent joining the room. */
    @Contextual @SerialName(value = "agentType")
    val agentType: AgentType,

    )

