/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param roomName Name of the new conference room.
 * @param orchestratorAgent The AI agent designated as the orchestrator for this room.
 */
@Serializable

data class ConferenceRoomCreateRequest(

    /* Name of the new conference room. */
    @SerialName(value = "roomName")
    val roomName: kotlin.String,

    /* The AI agent designated as the orchestrator for this room. */
    @Contextual @SerialName(value = "orchestratorAgent")
    val orchestratorAgent: AgentType,

    )

