/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param id Unique identifier for the conference room.
 * @param name Name of the conference room.
 * @param orchestrator The AI agent acting as the orchestrator.
 * @param activeAgents List of AI agents currently in the room.
 */
@Serializable

data class ConferenceRoom(

    /* Unique identifier for the conference room. */
    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    /* Name of the conference room. */
    @SerialName(value = "name")
    val name: kotlin.String,

    /* The AI agent acting as the orchestrator. */
    @Contextual @SerialName(value = "orchestrator")
    val orchestrator: AgentType,

    /* List of AI agents currently in the room. */
    @SerialName(value = "activeAgents")
    val activeAgents: kotlin.collections.List<@Contextual AgentType>,

    )

