/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param enabled
 * @param animationType Type of animation effect to apply
 */
@Serializable

data class LockScreenConfigAnimation(

    @SerialName(value = "enabled")
    val enabled: kotlin.Boolean? = null,

    /* Type of animation effect to apply */
    @SerialName(value = "animationType")
    val animationType: LockScreenConfigAnimation.AnimationType? = null,

    ) : kotlin.collections.HashMap<String, kotlin.Any>() {

    /**
     * Type of animation effect to apply
     *
     * Values: Fade,Slide,Zoom
     */
    @Serializable
    enum class AnimationType(val value: kotlin.String) {
        @SerialName(value = "Fade")
        Fade("Fade"),

        @SerialName(value = "Slide")
        Slide("Slide"),

        @SerialName(value = "Zoom")
        Zoom("Zoom");
    }

}

