package com.auraos.collab_canvas

import com.highcapable.yukihookapi.YukiHookAPI
import com.highcapable.yukihookapi.annotation.xposed.InjectYukiHookWithXposed
import com.highcapable.yukihookapi.hook.xposed.proxy.IYukiHookXposedInit

/**
 * Xposed Module Entry Class
 *
 * This class is automatically generated by YukiHookAPI.
 * Do not modify this class unless you know what you are doing.
 */
@InjectYukiHookWithXposed(
    isUsingResourcesHook = false, // Set to true if you need to hook resources
    isUsingXposedModuleLoader = true
)
object HookEntry : IYukiHookXposedInit {

    /**
     * Initialize module-wide configuration when the Xposed module is loaded.
     */
    override fun onInit() {
        YukiHookAPI.encase(this) {
            // Configure your module's behavior here
            configs {
                debuggable(BuildConfig.DEBUG) // Enable debugging in debug mode
                isEnableModulePrefsCache = true // Enable module prefs cache
            }
            
            // Your hook logic will go here
            // Example:
            // loadApp("com.example.app") {
            //     // Hook methods here
            // }
        }
    }
}
