/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param framework The UI framework (e.g., \"JetpackCompose\", \"XML Layout\").
 * @param description Natural language description of the UI component.
 * @param themeId ID of a specific theme to use for styling.
 */
@Serializable

data class GenerateUIComponentRequest(

    /* The UI framework (e.g., \"JetpackCompose\", \"XML Layout\"). */
    @SerialName(value = "framework")
    val framework: GenerateUIComponentRequest.Framework,

    /* Natural language description of the UI component. */
    @SerialName(value = "description")
    val description: kotlin.String,

    /* ID of a specific theme to use for styling. */
    @SerialName(value = "themeId")
    val themeId: kotlin.String? = null,

    ) {

    /**
     * The UI framework (e.g., \"JetpackCompose\", \"XML Layout\").
     *
     * Values: JetpackCompose,XMLLayout
     */
    @Serializable
    enum class Framework(val value: kotlin.String) {
        @SerialName(value = "JetpackCompose")
        JetpackCompose("JetpackCompose"),

        @SerialName(value = "XMLLayout")
        XMLLayout("XMLLayout");
    }

}

