/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Configuration for lock screen customization.
 *
 * @param clockConfig
 * @param animation
 * @param hapticFeedback
 */
@Serializable

data class LockScreenConfig(

    @Contextual @SerialName(value = "clockConfig")
    val clockConfig: LockScreenConfigClockConfig? = null,

    @Contextual @SerialName(value = "animation")
    val animation: LockScreenConfigAnimation? = null,

    @Contextual @SerialName(value = "hapticFeedback")
    val hapticFeedback: LockScreenConfigHapticFeedback? = null,

    ) : kotlin.collections.HashMap<String, kotlin.Any>()

