/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param tileId
 * @param labelColor Hex color code for tile label.
 * @param iconColor Hex color code for tile icon.
 * @param backgroundColor Hex color code for tile background.
 */
@Serializable

data class QuickSettingsConfigTilesInner(

    @SerialName(value = "tileId")
    val tileId: kotlin.String? = null,

    /* Hex color code for tile label. */
    @SerialName(value = "labelColor")
    val labelColor: kotlin.String? = null,

    /* Hex color code for tile icon. */
    @SerialName(value = "iconColor")
    val iconColor: kotlin.String? = null,

    /* Hex color code for tile background. */
    @SerialName(value = "backgroundColor")
    val backgroundColor: kotlin.String? = null,

    ) : kotlin.collections.HashMap<String, kotlin.Any>()

