/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param columns
 * @param rows
 */
@Serializable

data class QuickSettingsConfigLayout(

    @SerialName(value = "columns")
    val columns: kotlin.Int? = null,

    @SerialName(value = "rows")
    val rows: kotlin.Int? = null,

    )

