/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param top
 * @param bottom
 * @param horizontal
 */
@Serializable

data class QuickSettingsConfigPadding(

    @SerialName(value = "top")
    val top: kotlin.Int? = null,

    @SerialName(value = "bottom")
    val bottom: kotlin.Int? = null,

    @SerialName(value = "horizontal")
    val horizontal: kotlin.Int? = null,

    )

