// ...existing code...
// Moved from root src/test/kotlin to build-script-tests/src/test/kotlin/docs
// ...existing code...
// ...existing code...
// Moved from root src/test/kotlin to build-script-tests/src/test/kotlin/docs
// ...existing code...

