/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param agentType The type of the AI agent.
 * @param processingState Current processing state of the agent (e.g., \"IDLE\", \"PROCESSING\", \"ERROR\").
 * @param visionState Current vision/awareness state (e.g., \"ACTIVE\", \"MONITORING\", \"SLEEP\").
 * @param lastActivity Timestamp of the last activity.
 * @param currentTask Description of the current task being executed by the agent (if any).
 */
@Serializable

data class AgentStatus(

    /* The type of the AI agent. */
    @Contextual @SerialName(value = "agentType")
    val agentType: AgentType,

    /* Current processing state of the agent (e.g., \"IDLE\", \"PROCESSING\", \"ERROR\"). */
    @SerialName(value = "processingState")
    val processingState: kotlin.String,

    /* Current vision/awareness state (e.g., \"ACTIVE\", \"MONITORING\", \"SLEEP\"). */
    @SerialName(value = "visionState")
    val visionState: kotlin.String,

    /* Timestamp of the last activity. */
    @Contextual @SerialName(value = "lastActivity")
    val lastActivity: java.time.OffsetDateTime,

    /* Description of the current task being executed by the agent (if any). */
    @SerialName(value = "currentTask")
    val currentTask: kotlin.String? = null,

    )

