/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param prompt The prompt/instruction for the AI agent.
 * @param context Additional context (e.g., previous messages, data references).
 */
@Serializable

data class AgentProcessRequest(

    /* The prompt/instruction for the AI agent. */
    @SerialName(value = "prompt")
    val prompt: kotlin.String,

    /* Additional context (e.g., previous messages, data references). */
    @SerialName(value = "context")
    val context: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    )

