/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param accessToken The access token for API calls.
 * @param tokenType Type of the token (e.g., \"Bearer\").
 * @param expiresIn Time in seconds until the access token expires.
 * @param refreshToken Token to refresh the access token (if applicable).
 */
@Serializable

data class OAuthSuccess(

    /* The access token for API calls. */
    @SerialName(value = "accessToken")
    val accessToken: kotlin.String,

    /* Type of the token (e.g., \"Bearer\"). */
    @SerialName(value = "tokenType")
    val tokenType: kotlin.String,

    /* Time in seconds until the access token expires. */
    @SerialName(value = "expiresIn")
    val expiresIn: kotlin.Int,

    /* Token to refresh the access token (if applicable). */
    @SerialName(value = "refreshToken")
    val refreshToken: kotlin.String? = null,

    )

