/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param provider The OAuth provider (e.g., \"Google\", \"Firebase\", \"CustomAuth\").
 * @param redirectUri The URI to redirect to after successful authentication.
 */
@Serializable

data class OAuthStartRequest(

    /* The OAuth provider (e.g., \"Google\", \"Firebase\", \"CustomAuth\"). */
    @SerialName(value = "provider")
    val provider: kotlin.String,

    /* The URI to redirect to after successful authentication. */
    @Contextual @SerialName(value = "redirectUri")
    val redirectUri: java.net.URI,

    )

