/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param code The authorization code received from the OAuth provider.
 * @param state The state parameter to prevent CSRF attacks.
 */
@Serializable

data class OAuthCallbackRequest(

    /* The authorization code received from the OAuth provider. */
    @SerialName(value = "code")
    val code: kotlin.String,

    /* The state parameter to prevent CSRF attacks. */
    @SerialName(value = "state")
    val state: kotlin.String? = null,

    )

