/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param authUrl The URL the user should be redirected to for authentication.
 */
@Serializable

data class OAuthStartResponse(

    /* The URL the user should be redirected to for authentication. */
    @SerialName(value = "authUrl")
    val authUrl: kotlin.String,

    )

