/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param threatDetectionActive Indicates if real-time threat detection is active.
 * @param permissionsState Current state of key Android permissions where each key is a permission name and the value is a boolean indicating if it's granted (true) or denied (false).
 * @param activeThreats List of currently detected security threats.
 * @param lastScanTime Timestamp of the last security scan.
 */
@Serializable

data class SecurityState(

    /* Indicates if real-time threat detection is active. */
    @SerialName(value = "threatDetectionActive")
    val threatDetectionActive: kotlin.Boolean,

    /* Current state of key Android permissions where each key is a permission name and the value is a boolean indicating if it's granted (true) or denied (false). */
    @SerialName(value = "permissionsState")
    val permissionsState: kotlin.collections.Map<kotlin.String, kotlin.Boolean>,

    /* List of currently detected security threats. */
    @SerialName(value = "activeThreats")
    val activeThreats: kotlin.collections.List<kotlin.String>? = null,

    /* Timestamp of the last security scan. */
    @Contextual @SerialName(value = "lastScanTime")
    val lastScanTime: java.time.OffsetDateTime? = null,

    )

