/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param enabled
 * @param color Hex color code of the notch bar.
 * @param displayMode
 * @param customImageEnabled
 * @param customImageUrl
 */
@Serializable

data class SystemOverlayConfigNotchBar(

    @SerialName(value = "enabled")
    val enabled: kotlin.Boolean? = null,

    /* Hex color code of the notch bar. */
    @SerialName(value = "color")
    val color: kotlin.String? = null,

    @SerialName(value = "displayMode")
    val displayMode: SystemOverlayConfigNotchBar.DisplayMode? = null,

    @SerialName(value = "customImageEnabled")
    val customImageEnabled: kotlin.Boolean? = null,

    @SerialName(value = "customImageUrl")
    val customImageUrl: kotlin.String? = null,

    ) : kotlin.collections.HashMap<String, kotlin.Any>() {

    /**
     *
     *
     * Values: Minimal,Detailed,Hidden
     */
    @Serializable
    enum class DisplayMode(val value: kotlin.String) {
        @SerialName(value = "Minimal")
        Minimal("Minimal"),

        @SerialName(value = "Detailed")
        Detailed("Detailed"),

        @SerialName(value = "Hidden")
        Hidden("Hidden");
    }

}

