/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models


import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Real-time system performance metrics.
 *
 * @param batteryLevel Current battery charge level in percentage.
 * @param isCharging Indicates if the device is currently charging.
 * @param networkStatus Current network connectivity status (e.g., \"CONNECTED_WIFI\", \"CONNECTED_MOBILE\", \"DISCONNECTED\").
 * @param lastUpdated Timestamp of the last metric update.
 */
@Serializable

data class SystemMetrics(

    /* Current battery charge level in percentage. */
    @SerialName(value = "batteryLevel")
    val batteryLevel: kotlin.Int,

    /* Indicates if the device is currently charging. */
    @SerialName(value = "isCharging")
    val isCharging: kotlin.Boolean,

    /* Current network connectivity status (e.g., \"CONNECTED_WIFI\", \"CONNECTED_MOBILE\", \"DISCONNECTED\"). */
    @SerialName(value = "networkStatus")
    val networkStatus: kotlin.String,

    /* Timestamp of the last metric update. */
    @Contextual @SerialName(value = "lastUpdated")
    val lastUpdated: java.time.OffsetDateTime,

    )

